### ISSUE TITLE
Error "Cannot find hash of last commit on branch"

### ISSUE THREAD

**Issue by louis-l** [caprover/caprover-cli#119]
Hi there,

I have been using `AlexxNB/caprover-action@v1` to auto deploy on push for ages, but today it stops working.
I checked the Github action log and the last log was **Cannot find hash of last commit on branch "master".**

Here is the screenshot:
![Screen Shot 2022-04-19 at 9 03 39 am](https://user-images.githubusercontent.com/10172565/163890887-d7a2adb1-16cd-447b-9a1c-16d15421f8af.png)

I googled and found nothing exception this code: https://github.com/caprover/caprover-cli/blob/master/src/utils/ValidationsHandler.ts#L181

Can anyone shed some light here?

Cheers,

**Comment by githubsaturn** [comment]
I'd suggest you post the issue here: https://github.com/AlexxNB/caprover-action

**Comment by louis-l** [comment]
I thought about it, but then I check that action and its only job is to run `caprover deploy ...` command. So I thought it had something to do with the Caprover CLI.

**Comment by githubsaturn** [comment]
There is more to it. What's version of git? What environment it's running in? etc.

Can you reproduce it locally using `caprover deploy`?

**Comment by louis-l** [comment]
I just tested `caprover deploy` locally and it worked.

This is my deploy yml file:
```yml
name: CapRover Deployment
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: CapRover Deploy
        uses: AlexxNB/caprover-action@v1
        with:
          server: ${{secrets.CAPROVER_SERVER}}
          password: ${{secrets.CAPROVER_PASSWORD}}
          appname: ${{secrets.CAPROVER_APPNAME}}
          branch: master
      - name: Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: act10ns/slack@v1.5.0
        with:
          status: ${{ job.status }}
        if: always()
```

Again, it was working fine. Just today it stops working.

I checked `AlexxNB/caprover-action@v1` repo and it has not been changed in 2 years. 
- repo: https://github.com/AlexxNB/caprover-action
- run on `node:12-alpine` (see https://github.com/AlexxNB/caprover-action/blob/master/Dockerfile)

**Comment by githubsaturn** [comment]
Then it's something that changed on Github runners. Perhaps a different git version. Requires debugging. Try running this in your github runner and see what it prints:
```
git rev-parse master
```

**Comment by louis-l** [comment]
This is my test:
```yml
name: CapRover Deployment
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Test git command 🧪
        run: git rev-parse master
      - name: CapRover Deploy
        uses: AlexxNB/caprover-action@v1
        with:
          server: ${{secrets.CAPROVER_SERVER}}
          password: ${{secrets.CAPROVER_PASSWORD}}
          appname: ${{secrets.CAPROVER_APPNAME}}
          branch: master
      - name: Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: act10ns/slack@v1.5.0
        with:
          status: ${{ job.status }}
        if: always()
```

and here is the output:
![image](https://user-images.githubusercontent.com/10172565/163896689-4c2f5c96-9624-4c14-8cec-3a5eaa9fc869.png)
