### ISSUE TITLE
Can only deploy interactively (neither CLI arguments, nor config file work)

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [caprover/caprover-cli#36]
The options I supplied are these:
`caprover deploy --caproverUrl "https://captain.region.mydomain.com" --caproverApp myApp --branch master --caproverPassword "myPassword"`

Similarly in a `.yml` file:
```yml
---
branch: master
caproverApp: myApp
caproverPassword: 'myPassword'
caproverUrl: https://captain.region.mydomain.com
```

But with both ways, I get stuck at:
```
Ensuring authentication...
```
